apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m" # each container will request 20% of CPU so total here will be 60% 

#This will fail because we are creating a limit resource which won't have enough CPU for all the containers. 
 